# Generated by Django 3.1.14 on 2023-11-14 11:33

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, verbose_name='account number')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='balance')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
