# Generated by Django 3.1.14 on 2023-11-14 11:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('debit_amount', models.FloatField(default=0)),
                ('credit_amount', models.FloatField(default=0)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='transaction.transaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_records', to='wallet.wallet')),
            ],
        ),
    ]
